/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104583-ge5367b481b-20211118"
#endif /* AVUTIL_FFVERSION_H */
